### Register
POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
  "email": "dimas01@gmail.com",
  "password": "dimas123"
}

### Login
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
  "email": "dimas01@gmail.com",
  "password": "dimas123"
}

### authenticate
GET http://localhost:3000/api/v1/user/authenticate
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjk5MDQxMDExfQ.nQyQy4fHH5Lfk-vIXLoJDNvcR90xutvJ_Pxgq1AIw5o
